import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LanguageCode =
  | 'en' // English
  | 'hi' // हिन्दी (Hindi)
  | 'bn' // বাংলা (Bengali)
  | 'te' // తెలుగు (Telugu)
  | 'mr' // मराठी (Marathi)
  | 'ta' // தமிழ் (Tamil)
  | 'ur' // اردو (Urdu)
  | 'gu' // ગુજરાતી (Gujarati)
  | 'kn' // ಕನ್ನಡ (Kannada)
  | 'ml'; // മലയാളം (Malayalam)

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
  script: string;
  badge: string;
  speakerCount: string;
}

export const TOP_10_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', script: 'Latin', badge: 'EN', speakerCount: 'Global / Official' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', script: 'Devanagari', badge: 'HI', speakerCount: '528M+ speakers' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', script: 'Bengali', badge: 'BN', speakerCount: '97M+ speakers' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', script: 'Telugu', badge: 'TE', speakerCount: '83M+ speakers' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', script: 'Devanagari', badge: 'MR', speakerCount: '83M+ speakers' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', script: 'Tamil', badge: 'TA', speakerCount: '69M+ speakers' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', script: 'Perso-Arabic', badge: 'UR', speakerCount: '50M+ speakers' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', script: 'Gujarati', badge: 'GU', speakerCount: '46M+ speakers' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', script: 'Kannada', badge: 'KN', speakerCount: '44M+ speakers' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', script: 'Malayalam', badge: 'ML', speakerCount: '35M+ speakers' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Brand & Header
    'app.title': 'BHARAT Vuln Engine',
    'app.subtitle': 'TIRANGA 2.0 • NDMA OPS',
    'app.systemNominal': 'System Nominal',
    'app.allSystemsSecure': 'ALL SYSTEMS SECURE',
    'app.nationalGrid': 'National Disaster Response System • NDMA Tactical Grid',
    'app.selectLanguage': 'Select Language',
    'app.switchLanguage': 'Language',
    
    // Sidebar Navigation
    'nav.analytics': 'COMMAND & AI INTELLIGENCE',
    'nav.vulnerabilityMap': 'Vulnerability Map',
    'nav.dispatchMap': 'Dispatch Map',
    'nav.resourceManagement': 'Resource Management',
    'nav.prioritizationDashboard': 'Prioritization Dashboard',
    'nav.infrastructureStatus': 'Infrastructure Status',
    'nav.nationalStandby': 'NATIONAL STANDBY',
    'nav.standbyDesc': '36 States & UTs synchronized with NDMA & SDMA tactical relief grids.',
    'nav.gridActive': 'Grid: ACTIVE',
    'nav.hubsOnline': '68 Hubs Online',
    'nav.authorized': 'NDMA Authorized',
    'nav.teamName': 'Team Watch Dogs',

    // Vulnerability Map
    'vuln.title': 'Urban Vulnerability Engine',
    'vuln.activeSimulation': 'Active Simulation',
    'vuln.disasterType': 'Disaster Type',
    'vuln.severity': 'Severity Level',
    'vuln.epicenter': 'Epicenter',
    'vuln.radius': 'Impact Radius',
    'vuln.affectedDistricts': 'Affected Districts',
    'vuln.affectedPopulation': 'Affected Population',
    'vuln.criticalInfrastructure': 'Critical Infrastructure At Risk',
    'vuln.highRisk': 'High Risk',
    'vuln.mediumRisk': 'Medium Risk',
    'vuln.lowRisk': 'Low Risk',
    'vuln.flood': 'Flood & Inundation',
    'vuln.heatwave': 'Severe Heatwave',
    'vuln.cyclone': 'Tropical Cyclone',
    'vuln.earthquake': 'Seismic Tremor',

    // Infrastructure Status
    'infra.title': 'Critical Infrastructure Telemetry & Status Matrix',
    'infra.subtitle': 'Real-time multi-hazard telemetry tracking optical networks, drainage, emergency comms, and power grids across Indian states and metropolitan cities.',
    'infra.allIndiaTelemetry': 'All India Urban Infrastructure Telemetry',
    'infra.network': 'Cellular & Optical Networks',
    'infra.drainage': 'Stormwater Drainage Systems',
    'infra.comms': 'Emergency Communications',
    'infra.power': 'High-Voltage Power Grids',
    'infra.state': 'State',
    'infra.cityDistrict': 'City / District',
    'infra.lastUpdated': 'Last Updated',
    'infra.vulnScore': 'Overall Vulnerability Score',
    'infra.searchPlaceholder': 'Search state, city, capital, or infrastructure status...',
    'infra.showing': 'Showing',
    'infra.statesUts': 'States & UTs',
    'infra.clickToDrill': 'Click any state row to view constituent city & district telemetry',
    'infra.healthy': 'Optimal',
    'infra.compromised': 'Strained',
    'infra.failing': 'Critical',
    'infra.statusAll': 'All Statuses',
    'infra.statusOperational': 'Operational Only',
    'infra.statusDegraded': 'Degraded / Critical Only',

    // Prioritization Dashboard
    'prior.title': 'NDMA AI Prioritization & Intervention Command',
    'prior.subtitle': 'Dynamic multi-criteria decision engine synthesizing real-time hazard severity, population exposure, and adaptive capacity deficit across India.',
    'prior.scope': 'Geographic Scope',
    'prior.allZones': 'All Zones (Nationwide)',
    'prior.district': 'District / Urban Zone',
    'prior.compositeVuln': 'Composite Vulnerability Index',
    'prior.exposureScore': 'Exposure Score',
    'prior.sensitivityScore': 'Sensitivity Score',
    'prior.adaptiveDeficit': 'Adaptive Capacity Deficit',
    'prior.recommendedAction': 'Recommended NDMA / SDRF Action',
    'prior.urgency': 'Urgency',
    'prior.hazardProgression': '24-Hour Projected Hazard Curve',
    'prior.dispatchSuggestion': 'Recommended Deployment Package',
    'prior.evacuationReadiness': 'Evacuation Readiness',

    // Dispatch Map
    'disp.title': 'Tactical Dispatch & Logistics Matrix',
    'disp.subtitle': 'Geo-spatial routing & supply chain coordinator connecting NDMA central depots with disaster epicenters.',
    'disp.reliefStocks': 'State Relief Stocks',
    'disp.activeDispatches': 'Active Dispatches',
    'disp.authorizeDispatch': 'Authorize Emergency Dispatch',
    'disp.noDispatches': 'No Active Dispatches in',
    'disp.noDispatchesDesc': 'All NDRF, SDRF, and IAF relief convoys are currently on standby at designated state warehouses.',
    'disp.initiateRelief': 'Initiate Tactical Relief Dispatch',
    'disp.warehouse': 'Origin Depot / Godown',
    'disp.target': 'Target District',
    'disp.transportMode': 'Transport Corridor',
    'disp.eta': 'Estimated Arrival (ETA)',
    'disp.status': 'Mission Status',
    'disp.inTransit': 'In Transit',
    'disp.arrived': 'Arrived & Active',
    'disp.teleportState': 'Click district to inspect and focus parent state',

    // Resource Management
    'res.title': 'National & State Disaster Logistics Command',
    'res.subtitle': 'NDRF Battalions, State Reserves, Heavy Machinery, and Airlift Readiness',
    'res.ndrfBattalions': 'NDRF Battalions',
    'res.sdrfReserves': 'SDRF State Reserves',
    'res.airAssets': 'Aviation & Helicopters',
    'res.boatsPumps': 'Boats & Water Pumps',
    'res.rationShelter': 'Ration & Temporary Shelter Kits',
    'res.powerTelecom': 'Emergency Power & Telecom Sets',
    'res.deploy': 'Deploy Asset',
    'res.reserveLevel': 'Reserve Level',
    'res.readiness': 'Operational Readiness',

    // Common
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.export': 'Export Data',
    'common.refresh': 'Refresh Feed',
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.details': 'View Details',
    'common.critical': 'CRITICAL',
    'common.high': 'HIGH',
    'common.moderate': 'MODERATE',
    'common.low': 'LOW',
    'common.live': 'LIVE',
  },
  hi: {
    // Brand & Header
    'app.title': 'भारत आपदा भेद्यता इंजन',
    'app.subtitle': 'तिरंगा 2.0 • राष्ट्रीय आपदा प्रबंधन प्राधिकरण (NDMA)',
    'app.systemNominal': 'प्रणाली सामान्य',
    'app.allSystemsSecure': 'सभी प्रणालियां सुरक्षित',
    'app.nationalGrid': 'राष्ट्रीय आपदा मोचन प्रणाली • NDMA रणनीतिक ग्रिड',
    'app.selectLanguage': 'भाषा चुनें',
    'app.switchLanguage': 'भाषा',

    // Sidebar Navigation
    'nav.analytics': 'कमांड व एआई इंटेलिजेंस',
    'nav.vulnerabilityMap': 'भेद्यता मानचित्र (GIS)',
    'nav.dispatchMap': 'डिस्पैच व लॉजिस्टिक्स मैप',
    'nav.resourceManagement': 'संसाधन प्रबंधन',
    'nav.prioritizationDashboard': 'प्राथमिकता डैशबोर्ड',
    'nav.infrastructureStatus': 'बुनियादी ढांचा स्थिति',
    'nav.nationalStandby': 'राष्ट्रीय तत्परता',
    'nav.standbyDesc': '36 राज्य और केंद्र शासित प्रदेश NDMA और SDMA राहत ग्रिड से समन्वयित हैं।',
    'nav.gridActive': 'ग्रिड: सक्रिय',
    'nav.hubsOnline': '68 केंद्र ऑनलाइन',
    'nav.authorized': 'NDMA अधिकृत',
    'nav.teamName': 'टीम वॉच डॉग्स',

    // Vulnerability Map
    'vuln.title': 'शहरी भेद्यता इंजन',
    'vuln.activeSimulation': 'सक्रिय आपदा अनुकरण',
    'vuln.disasterType': 'आपदा का प्रकार',
    'vuln.severity': 'गंभीरता स्तर',
    'vuln.epicenter': 'आपदा केंद्र',
    'vuln.radius': 'प्रभाव त्रिज्या',
    'vuln.affectedDistricts': 'प्रभावित जिले',
    'vuln.affectedPopulation': 'प्रभावित जनसंख्या',
    'vuln.criticalInfrastructure': 'जोखिम में बुनियादी ढांचा',
    'vuln.highRisk': 'उच्च जोखिम',
    'vuln.mediumRisk': 'मध्यम जोखिम',
    'vuln.lowRisk': 'कम जोखिम',
    'vuln.flood': 'बाढ़ व जलभराव',
    'vuln.heatwave': 'भीषण लू (हीटवेव)',
    'vuln.cyclone': 'चक्रवात तूफान',
    'vuln.earthquake': 'भूकंप झटका',

    // Infrastructure Status
    'infra.title': 'महत्वपूर्ण बुनियादी ढांचा टेलीमेट्री व स्थिति मैट्रिक्स',
    'infra.subtitle': 'भारतीय राज्यों और महानगरों में ऑप्टिकल नेटवर्क, जल निकासी, आपातकालीन संचार और बिजली ग्रिड की वास्तविक समय ट्रैकिंग।',
    'infra.allIndiaTelemetry': 'अखिल भारतीय शहरी बुनियादी ढांचा टेलीमेट्री',
    'infra.network': 'सेल्युलर व ऑप्टिकल नेटवर्क',
    'infra.drainage': 'तूफानी जल निकासी प्रणालियां',
    'infra.comms': 'आपातकालीन संचार नेटवर्क',
    'infra.power': 'उच्च-वोल्टेज विद्युत ग्रिड',
    'infra.state': 'राज्य',
    'infra.cityDistrict': 'शहर / जिला',
    'infra.lastUpdated': 'अंतिम अद्यतन',
    'infra.vulnScore': 'समग्र भेद्यता स्कोर',
    'infra.searchPlaceholder': 'राज्य, शहर, राजधानी या बुनियादी ढांचे की स्थिति खोजें...',
    'infra.showing': 'प्रदर्शित',
    'infra.statesUts': 'राज्य और केंद्र शासित प्रदेश',
    'infra.clickToDrill': 'शहर और जिला टेलीमेट्री देखने के लिए किसी भी राज्य पर क्लिक करें',
    'infra.healthy': 'उत्कृष्ट',
    'infra.compromised': 'तनावग्रस्त',
    'infra.failing': 'गंभीर',
    'infra.statusAll': 'सभी स्थितियां',
    'infra.statusOperational': 'केवल सुचारू',
    'infra.statusDegraded': 'केवल प्रभावित/गंभीर',

    // Prioritization Dashboard
    'prior.title': 'NDMA एआई प्राथमिकता व हस्तक्षेप कमांड',
    'prior.subtitle': 'वास्तविक समय आपदा गंभीरता, जनसंख्या जोखिम और अनुकूलन क्षमता की कमी का विश्लेषण करने वाला निर्णय इंजन।',
    'prior.scope': 'भौगोलिक दायरा',
    'prior.allZones': 'सभी क्षेत्र (संपूर्ण भारत)',
    'prior.district': 'जिला / शहरी क्षेत्र',
    'prior.compositeVuln': 'समग्र भेद्यता सूचकांक',
    'prior.exposureScore': 'जोखिम प्रसार स्कोर',
    'prior.sensitivityScore': 'संवेदनशीलता स्कोर',
    'prior.adaptiveDeficit': 'अनुकूलन क्षमता घाटा',
    'prior.recommendedAction': 'अनुशंसित NDMA / SDRF कार्रवाई',
    'prior.urgency': 'तात्कालिकता',
    'prior.hazardProgression': '24-घंटे का अनुमानित खतरा ग्राफ',
    'prior.dispatchSuggestion': 'अनुशंसित राहत पैकेज',
    'prior.evacuationReadiness': 'निकासी तत्परता',

    // Dispatch Map
    'disp.title': 'रणनीतिक डिस्पैच व रसद मैट्रिक्स',
    'disp.subtitle': 'NDMA केंद्रीय डिपो को आपदा केंद्रों से जोड़ने वाला भू-स्थानिक रूटिंग व आपूर्ति समन्वयक।',
    'disp.reliefStocks': 'राज्य राहत भंडार',
    'disp.activeDispatches': 'सक्रिय राहत काफिले',
    'disp.authorizeDispatch': 'आपातकालीन राहत डिस्पैच स्वीकृत करें',
    'disp.noDispatches': 'में कोई सक्रिय काफिला नहीं है',
    'disp.noDispatchesDesc': 'सभी NDRF, SDRF और वायुसेना राहत काफिले वर्तमान में नामित राज्य गोदामों पर स्टैंडबाय पर हैं।',
    'disp.initiateRelief': 'राहत काफिला रवाना करें',
    'disp.warehouse': 'स्रोत डिपो / गोदाम',
    'disp.target': 'गंतव्य जिला',
    'disp.transportMode': 'परिवहन गलियारा',
    'disp.eta': 'अनुमानित आगमन समय (ETA)',
    'disp.status': 'मिशन स्थिति',
    'disp.inTransit': 'मार्ग में (In Transit)',
    'disp.arrived': 'पहुंच चुका व सक्रिय',
    'disp.teleportState': 'राज्य पर ध्यान केंद्रित करने हेतु जिले पर क्लिक करें',

    // Resource Management
    'res.title': 'राष्ट्रीय एवं राज्य आपदा रसद कमान',
    'res.subtitle': 'NDRF बटालियन, राज्य भंडार, भारी मशीनरी और हवाई परिवहन तत्परता',
    'res.ndrfBattalions': 'NDRF बटालियन',
    'res.sdrfReserves': 'SDRF राज्य भंडार',
    'res.airAssets': 'विमानन व हेलीकॉप्टर',
    'res.boatsPumps': 'नावें और जल निकासी पंप',
    'res.rationShelter': 'राशन और अस्थायी आश्रय किट',
    'res.powerTelecom': 'आपातकालीन जनरेटर व संचार सेट',
    'res.deploy': 'संसाधन तैनात करें',
    'res.reserveLevel': 'भंडार स्तर',
    'res.readiness': 'परिचालन तत्परता',

    // Common
    'common.search': 'खोजें...',
    'common.filter': 'फ़िल्टर',
    'common.export': 'डेटा निर्यात करें',
    'common.refresh': 'ताज़ा करें',
    'common.close': 'बंद करें',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.details': 'विवरण देखें',
    'common.critical': 'अति गंभीर',
    'common.high': 'उच्च',
    'common.moderate': 'मध्यम',
    'common.low': 'सामान्य',
    'common.live': 'लाइव',
  },
  bn: {
    // Bengali
    'app.title': 'ভারত দুর্যোগ সংবেদনশীলতা ইঞ্জিন',
    'app.subtitle': 'তেরঙ্গা ২.০ • এনডিএমএ কমান্ড',
    'app.systemNominal': 'সিস্টেম স্বাভাবিক',
    'app.allSystemsSecure': 'সকল সিস্টেম সুরক্ষিত',
    'app.nationalGrid': 'জাতীয় দুর্যোগ মোকাবেলা ব্যবস্থা • এনডিএমএ ট্যাকটিক্যাল গ্রিড',
    'app.selectLanguage': 'ভাষা নির্বাচন করুন',
    'app.switchLanguage': 'ভাষা',
    'nav.analytics': 'কমান্ড ও এআই বুদ্ধিমত্তা',
    'nav.vulnerabilityMap': 'সংবেদনশীলতা মানচিত্র',
    'nav.dispatchMap': 'ত্রাণ প্রেরণ মানচিত্র',
    'nav.resourceManagement': 'সম্পদ ব্যবস্থাপনা',
    'nav.prioritizationDashboard': 'অগ্রাধিকার ড্যাশবোর্ড',
    'nav.infrastructureStatus': 'পরিকাঠামোর স্থিতি',
    'nav.nationalStandby': 'জাতীয় প্রস্তুতি',
    'nav.standbyDesc': '৩৬টি রাজ্য ও কেন্দ্রশাসিত অঞ্চল এনডিএমএ ত্রাণ গ্রিডের সাথে যুক্ত।',
    'nav.gridActive': 'গ্রিড: সক্রিয়',
    'nav.hubsOnline': '৬৮টি কেন্দ্র সক্রিয়',
    'nav.authorized': 'এনডিএমএ অনুমোদিত',
    'nav.teamName': 'টিম ওয়াচ ডগস',
    'vuln.title': 'নগর সংবেদনশীলতা ইঞ্জিন',
    'vuln.activeSimulation': 'সক্রিয় দুর্যোগ সিমুলেশন',
    'vuln.disasterType': 'দুর্যোগের ধরন',
    'vuln.severity': 'তীব্রতার মাত্রা',
    'vuln.epicenter': 'কেন্দ্রবিন্দু',
    'vuln.radius': 'প্রভাব ব্যাসার্ধ',
    'vuln.affectedDistricts': 'ক্ষতিগ্রস্ত জেলা',
    'vuln.affectedPopulation': 'প্রভাবিত জনসংখ্যা',
    'vuln.criticalInfrastructure': 'ঝুঁকিপূর্ণ পরিকাঠামো',
    'vuln.highRisk': 'উচ্চ ঝুঁকি',
    'vuln.mediumRisk': 'মাঝারি ঝুঁকি',
    'vuln.lowRisk': 'কম ঝুঁকি',
    'vuln.flood': 'বন্যা ও প্লাবন',
    'vuln.heatwave': 'তীব্র তাপপ্রবাহ',
    'vuln.cyclone': 'ঘূর্ণিঝড়',
    'vuln.earthquake': 'ভূমিকম্প',
    'infra.title': 'গুরুত্বপূর্ণ পরিকাঠামো টেলিমেট্রি ও স্ট্যাটাস ম্যাট্রিক্স',
    'infra.subtitle': 'ভারতের রাজ্য ও মেট্রোপলিটনে অপটিক্যাল নেটওয়ার্ক, ড্রেনেজ ও বিদ্যুৎ গ্রিডের রিয়েল-টাইম ট্র্যাকিং।',
    'infra.allIndiaTelemetry': 'সর্বভারতীয় নগর পরিকাঠামো টেলিমেট্রি',
    'infra.network': 'সেলুলার ও অপটিক্যাল নেটওয়ার্ক',
    'infra.drainage': 'ঝড় জল নিষ্কাশন ব্যবস্থা',
    'infra.comms': 'জরুরী যোগাযোগ ব্যবস্থা',
    'infra.power': 'উচ্চ-ভোল্টেজ বিদ্যুৎ গ্রিড',
    'infra.state': 'রাজ্য',
    'infra.cityDistrict': 'শহর / জেলা',
    'infra.lastUpdated': 'সর্বশেষ আপডেট',
    'infra.vulnScore': 'সামগ্রিক সংবেদনশীলতা স্কোর',
    'infra.searchPlaceholder': 'রাজ্য, শহর বা পরিকাঠামো খুঁজুন...',
    'infra.showing': 'প্রদর্শিত',
    'infra.statesUts': 'রাজ্য ও কেন্দ্রশাসিত অঞ্চল',
    'infra.clickToDrill': 'বিস্তারিত দেখতে যেকোনো রাজ্যে ক্লিক করুন',
    'infra.healthy': 'অনুকূল',
    'infra.compromised': 'ক্ষতিগ্রস্ত',
    'infra.failing': 'সংকটজনক',
    'infra.statusAll': 'সকল স্থিতি',
    'infra.statusOperational': 'শুধুমাত্র সক্রিয়',
    'infra.statusDegraded': 'সংকটজনক মাত্র',
    'prior.title': 'এনডিএমএ এআই অগ্রাধিকার ও হস্তক্ষেপ কমান্ড',
    'prior.subtitle': 'রিয়েল-টাইম দুর্যোগ তীব্রতা ও জনসংখ্যা ঝুঁকি বিশ্লেষণের সিদ্ধান্ত ইঞ্জিন।',
    'prior.scope': 'ভৌগোলিক পরিধি',
    'prior.allZones': 'সকল অঞ্চল (সমগ্র ভারত)',
    'prior.district': 'জেলা / নগর অঞ্চল',
    'prior.compositeVuln': 'যৌগিক সংবেদনশীলতা সূচক',
    'prior.exposureScore': 'ঝুঁকি এক্সপোজার স্কোর',
    'prior.sensitivityScore': 'সংবেদনশীলতা স্কোর',
    'prior.adaptiveDeficit': 'অভিযোজন ক্ষমতা ঘাটতি',
    'prior.recommendedAction': 'সুপারিশকৃত ত্রাণ ব্যবস্থা',
    'prior.urgency': 'জরুরী মাত্রা',
    'prior.hazardProgression': '২৪ ঘণ্টার পূর্বাভাস গ্রাফ',
    'prior.dispatchSuggestion': 'প্রস্তাবিত ত্রাণ সামগ্রী',
    'prior.evacuationReadiness': 'স্থানান্তর প্রস্তুতি',
    'disp.title': 'কৌশলগত ত্রাণ ও সরবরাহ ম্যাট্রিক্স',
    'disp.subtitle': 'কেন্দ্রীয় ডিপো থেকে দুর্যোগ কেন্দ্রে দ্রুত সরবরাহ সমন্বয়কারী।',
    'disp.reliefStocks': 'রাজ্য ত্রাণ মজুদ',
    'disp.activeDispatches': 'সক্রিয় ত্রাণ বহর',
    'disp.authorizeDispatch': 'জরুরী ত্রাণ অনুমোদন করুন',
    'disp.noDispatches': 'কোনো সক্রিয় বহর নেই:',
    'disp.noDispatchesDesc': 'সকল এনডিআরএফ ও এসডিআরএফ দল বর্তমানে রাজ্য গুদামে প্রস্তুত রয়েছে।',
    'disp.initiateRelief': 'ত্রাণ বহর পাঠান',
    'disp.warehouse': 'উৎস ডিপো / গুদাম',
    'disp.target': 'গন্তব্য জেলা',
    'disp.transportMode': 'পরিবহন পথ',
    'disp.eta': 'আনুমানিক পৌঁছানোর সময়',
    'disp.status': 'অভিযান স্থিতি',
    'disp.inTransit': 'যাত্রাপথে (In Transit)',
    'disp.arrived': 'উপস্থিত ও সক্রিয়',
    'disp.teleportState': 'রাজ্য ফোকাস করতে জেলায় ক্লিক করুন',
    'res.title': 'জাতীয় ও রাজ্য দুর্যোগ সরবরাহ কমাণ্ড',
    'res.subtitle': 'এনডিআরএফ ব্যাটালিয়ন, মজুত ও বিমান উদ্ধার প্রস্তুতি',
    'res.ndrfBattalions': 'এনডিআরএফ ব্যাটালিয়ন',
    'res.sdrfReserves': 'এসডিআরএফ মজুত',
    'res.airAssets': 'বিমান ও হেলিকপ্টার',
    'res.boatsPumps': 'নৌকা ও পাম্প',
    'res.rationShelter': 'ত্রাণ ও অস্থায়ী তাঁবু',
    'res.powerTelecom': 'জরুরী জেনারেটর সেট',
    'res.deploy': 'নিয়োগ করুন',
    'res.reserveLevel': 'মজুত স্তর',
    'res.readiness': 'প্রস্তুতি',
    'common.search': 'অনুসন্ধান...',
    'common.filter': 'ফিল্টার',
    'common.export': 'রপ্তানি',
    'common.refresh': 'রিফ্রেশ',
    'common.close': 'বন্ধ করুন',
    'common.cancel': 'বাতিল',
    'common.confirm': 'নিশ্চিত করুন',
    'common.details': 'বিস্তারিত',
    'common.critical': 'সংকটজনক',
    'common.high': 'উচ্চ',
    'common.moderate': 'মাঝারি',
    'common.low': 'কম',
    'common.live': 'সরাসরি',
  },
  te: {
    // Telugu
    'app.title': 'భారత్ విపత్తు దుర్బలత్వ ఇంజిన్',
    'app.subtitle': 'త్రివర్ణ 2.0 • NDMA కమాండ్',
    'app.systemNominal': 'వ్యవస్థ సాధారణం',
    'app.allSystemsSecure': 'అన్ని వ్యవస్థలు సురక్షితం',
    'app.nationalGrid': 'జాతీయ విపత్తు ప్రతిస్పందన వ్యవస్థ • NDMA వ్యూహాత్మక గ్రిడ్',
    'app.selectLanguage': 'భాషను ఎంచుకోండి',
    'app.switchLanguage': 'భాష',
    'nav.analytics': 'కమాండ్ & AI ఇంటెలిజెన్స్',
    'nav.vulnerabilityMap': 'దుర్బలత్వ పటం (GIS)',
    'nav.dispatchMap': 'డిస్పాచ్ & లాజిస్టిక్స్ మ్యాప్',
    'nav.resourceManagement': 'వనరుల నిర్వహణ',
    'nav.prioritizationDashboard': 'ప్రాధాన్యత డ్యాష్‌బోర్డ్',
    'nav.infrastructureStatus': 'మౌలిక సదుపాయాల స్థితి',
    'nav.nationalStandby': 'జాతీయ సన్నద్ధత',
    'nav.standbyDesc': '36 రాష్ట్రాలు & కేంద్రపాలిత ప్రాంతాలు NDMA గ్రిడ్‌తో సమన్వయం చేయబడ్డాయి.',
    'nav.gridActive': 'గ్రిడ్: క్రియాశీలకం',
    'nav.hubsOnline': '68 కేంద్రాలు ఆన్‌లైన్',
    'nav.authorized': 'NDMA ప్రామాణీకరించబడింది',
    'nav.teamName': 'టీమ్ వాచ్ డాగ్స్',
    'vuln.title': 'పట్టణ విపత్తు దుర్బలత్వ వ్యవస్థ',
    'vuln.activeSimulation': 'ప్రస్తుత విపత్తు అనుకరణ',
    'vuln.disasterType': 'విపత్తు రకం',
    'vuln.severity': 'తీవ్రత స్థాయి',
    'vuln.epicenter': 'విపత్తు కేంద్రం',
    'vuln.radius': 'ప్రభావ పరిధి',
    'vuln.affectedDistricts': 'ప్రభావిత జిల్లాలు',
    'vuln.affectedPopulation': 'ప్రభావిత జనాభా',
    'vuln.criticalInfrastructure': 'ప్రమాదంలో ఉన్న మౌలిక వసతులు',
    'vuln.highRisk': 'అధిక ప్రమాదం',
    'vuln.mediumRisk': 'మధ్యస్థ ప్రమాదం',
    'vuln.lowRisk': 'తక్కువ ప్రమాదం',
    'vuln.flood': 'వరదలు & ముంపు',
    'vuln.heatwave': 'తీవ్రమైన ఎండగాలులు',
    'vuln.cyclone': 'తుఫాను',
    'vuln.earthquake': 'భూకంపం',
    'infra.title': 'మౌలిక సదుపాయాల టెలిమెట్రీ & స్థితి మాత్రిక',
    'infra.subtitle': 'ఆప్టికల్ నెట్‌వర్క్‌లు, డ్రైనేజీ, అత్యవసర సమాచారం & విద్యుత్ గ్రిడ్‌ల రియల్-టైమ్ పర్యవేక్షణ.',
    'infra.allIndiaTelemetry': 'అఖిల భారత పట్టణ మౌలిక సదుపాయాల టెలిమెట్రీ',
    'infra.network': 'సెల్యులార్ & ఆప్టికల్ నెట్‌వర్క్‌లు',
    'infra.drainage': 'వర్షపు నీటి డ్రైనేజీ వ్యవస్థలు',
    'infra.comms': 'అత్యవసర సమాచార వ్యవస్థ',
    'infra.power': 'హై-వోల్టేజ్ విద్యుత్ గ్రిడ్‌లు',
    'infra.state': 'రాష్ట్రం',
    'infra.cityDistrict': 'నగరం / జిల్లా',
    'infra.lastUpdated': 'చివరి నవీకరణ',
    'infra.vulnScore': 'మొత్తం దుర్బలత్వ స్కోరు',
    'infra.searchPlaceholder': 'రాష్ట్రం, నగరం లేదా స్థితిని శోధించండి...',
    'infra.showing': 'చూపుతున్నవి',
    'infra.statesUts': 'రాష్ట్రాలు & కేంద్రపాలిత ప్రాంతాలు',
    'infra.clickToDrill': 'వివరాలు చూడటానికి ఏదైనా రాష్ట్రాన్ని క్లిక్ చేయండి',
    'infra.healthy': 'అద్భుతం',
    'infra.compromised': 'ప్రభావితం',
    'infra.failing': 'తీవ్ర సంక్షోభం',
    'infra.statusAll': 'అన్ని స్థితులు',
    'infra.statusOperational': 'క్రియాశీలమైనవి మాత్రమే',
    'infra.statusDegraded': 'ప్రభావితమైనవి మాత్రమే',
    'prior.title': 'NDMA AI ప్రాధాన్యతా కమాండ్',
    'prior.subtitle': 'విపత్తు తీవ్రత మరియు జనాభా ప్రమాదాన్ని విశ్లేషించే నిర్ణయ వ్యవస్థ.',
    'prior.scope': 'భౌగోళిక పరిధి',
    'prior.allZones': 'అన్ని ప్రాంతాలు (భారతదేశం అంతటా)',
    'prior.district': 'జిల్లా / పట్టణ ప్రాంతం',
    'prior.compositeVuln': 'సమగ్ర దుర్బలత్వ సూచిక',
    'prior.exposureScore': 'ఎక్స్‌పోజర్ స్కోరు',
    'prior.sensitivityScore': 'సున్నితత్వ స్కోరు',
    'prior.adaptiveDeficit': 'సమర్థత లోటు',
    'prior.recommendedAction': 'సిఫార్సు చేసిన సహాయక చర్య',
    'prior.urgency': 'అత్యవసరత',
    'prior.hazardProgression': '24-గంటల ముందస్తు ప్రమాద సూచిక',
    'prior.dispatchSuggestion': 'సిఫార్సు చేయబడిన సహాయ ప్యాకేజీ',
    'prior.evacuationReadiness': 'తరలింపు సన్నద్ధత',
    'disp.title': 'వ్యూహాత్మక రవాణా & సహాయక మ్యాప్',
    'disp.subtitle': 'డిపోల నుండి విపత్తు ప్రాంతాలకు వేగవంతమైన సహాయ రవాణా.',
    'disp.reliefStocks': 'రాష్ట్ర సహాయ నిల్వలు',
    'disp.activeDispatches': 'క్రియాశీల సహాయ కాన్వాయ్‌లు',
    'disp.authorizeDispatch': 'అత్యవసర సహాయాన్ని ఆమోదించండి',
    'disp.noDispatches': 'లో క్రియాశీల కాన్వాయ్‌లు లేవు:',
    'disp.noDispatchesDesc': 'అన్ని ఎన్డీఆర్ఎఫ్ బృందాలు ప్రస్తుతం రాష్ట్ర గిడ్డంగులలో సిద్ధంగా ఉన్నాయి.',
    'disp.initiateRelief': 'సహాయ బృందాన్ని పంపండి',
    'disp.warehouse': 'మూల డిపో / గిడ్డంగి',
    'disp.target': 'లక్ష్య జిల్లా',
    'disp.transportMode': 'రవాణా మార్గం',
    'disp.eta': 'చేరుకునే అంచనా సమయం',
    'disp.status': 'మిషన్ స్థితి',
    'disp.inTransit': 'మార్గంలో (In Transit)',
    'disp.arrived': 'చేరుకుంది & క్రియాశీలకం',
    'disp.teleportState': 'రాష్ట్రాన్ని కేంద్రీకరించడానికి జిల్లాను క్లిక్ చేయండి',
    'res.title': 'జాతీయ & రాష్ట్ర విపత్తు రవాణా కమాండ్',
    'res.subtitle': 'NDRF బెటాలియన్లు, నిల్వలు మరియు హెలికాప్టర్ సన్నద్ధత',
    'res.ndrfBattalions': 'NDRF బెటాలియన్లు',
    'res.sdrfReserves': 'SDRF నిల్వలు',
    'res.airAssets': 'విమానయాన వనరులు',
    'res.boatsPumps': 'పడవలు & పంపులు',
    'res.rationShelter': 'రేషన్ & తాత్కాలిక గుడారాలు',
    'res.powerTelecom': 'జనరేటర్లు & కమ్యూనికేషన్ సెట్లు',
    'res.deploy': 'వనరులను కేటాయించండి',
    'res.reserveLevel': 'నిల్వ స్థాయి',
    'res.readiness': 'కార్యాచరణ సన్నద్ధత',
    'common.search': 'శోధించండి...',
    'common.filter': 'ఫిల్టర్',
    'common.export': 'ఎగుమతి',
    'common.refresh': 'రిఫ్రెష్',
    'common.close': 'మూసివేయి',
    'common.cancel': 'రద్దు చేయి',
    'common.confirm': 'ధృవీకరించు',
    'common.details': 'వివరాలు',
    'common.critical': 'తీవ్ర సంక్షోభం',
    'common.high': 'అధికం',
    'common.moderate': 'మధ్యస్థం',
    'common.low': 'సాధారణం',
    'common.live': 'లైవ్',
  },
  mr: {
    // Marathi
    'app.title': 'भारत आपत्ती असुरक्षितता इंजिन',
    'app.subtitle': 'तिरंगा २.० • NDMA कमांड',
    'app.systemNominal': 'प्रणाली सामान्य',
    'app.allSystemsSecure': 'सर्व प्रणाली सुरक्षित',
    'app.nationalGrid': 'राष्ट्रीय आपत्ती निवारण प्रणाली • NDMA रणनीतिक ग्रिड',
    'app.selectLanguage': 'भाषा निवडा',
    'app.switchLanguage': 'भाषा',
    'nav.analytics': 'कमांड आणि एआय बुद्धिमत्ता',
    'nav.vulnerabilityMap': 'असुरक्षितता नकाशा (GIS)',
    'nav.dispatchMap': 'डिस्पॅच आणि लॉजिस्टिक्स नकाशा',
    'nav.resourceManagement': 'संसाधन व्यवस्थापन',
    'nav.prioritizationDashboard': 'प्राधान्यता डॅशबोर्ड',
    'nav.infrastructureStatus': 'पायाभूत सुविधा स्थिती',
    'nav.nationalStandby': 'राष्ट्रीय सज्जता',
    'nav.standbyDesc': '३६ राज्ये आणि केंद्रशासित प्रदेश NDMA आणि SDMA ग्रिडशी जोडलेले आहेत.',
    'nav.gridActive': 'ग्रिड: सक्रिय',
    'nav.hubsOnline': '६८ हब ऑनलाइन',
    'nav.authorized': 'NDMA अधिकृत',
    'nav.teamName': 'टीम वॉच डॉग्ज',
    'vuln.title': 'शहरी असुरक्षितता इंजिन',
    'vuln.activeSimulation': 'सक्रिय आपत्ती सिम्युलेशन',
    'vuln.disasterType': 'आपत्तीचा प्रकार',
    'vuln.severity': 'तीव्रता पातळी',
    'vuln.epicenter': 'आपत्ती केंद्र',
    'vuln.radius': 'प्रभाव त्रिज्या',
    'vuln.affectedDistricts': 'प्रभावित जिल्हे',
    'vuln.affectedPopulation': 'प्रभावित लोकसंख्या',
    'vuln.criticalInfrastructure': 'धोक्यात असलेल्या पायाभूत सुविधा',
    'vuln.highRisk': 'उच्च धोका',
    'vuln.mediumRisk': 'मध्यम धोका',
    'vuln.lowRisk': 'कमी धोका',
    'vuln.flood': 'पूर व पाणी साचणे',
    'vuln.heatwave': 'उष्णतेची लाट (Heatwave)',
    'vuln.cyclone': 'चक्रीवादळ',
    'vuln.earthquake': 'भूकंप',
    'infra.title': 'महत्त्वाच्या पायाभूत सुविधांची टेलिमेट्री व स्थिती',
    'infra.subtitle': 'ऑप्टिकल नेटवर्क, ड्रेनेज, आणीबाणी संप्रेषण आणि वीज ग्रिडचे रिअल-टाइम ट्रॅकिंग.',
    'infra.allIndiaTelemetry': 'अखिल भारतीय नागरी पायाभूत सुविधा टेलिमेट्री',
    'infra.network': 'सेल्युलर व ऑप्टिकल नेटवर्क',
    'infra.drainage': 'पावसाळी पाणी निचरा प्रणाली',
    'infra.comms': 'आणीबाणी संप्रेषण नेटवर्क',
    'infra.power': 'उच्च-व्होल्टेज वीज ग्रिड',
    'infra.state': 'राज्य',
    'infra.cityDistrict': 'शहर / जिल्हा',
    'infra.lastUpdated': 'शेवटचे अपडेट',
    'infra.vulnScore': 'एकूण असुरक्षितता स्कोअर',
    'infra.searchPlaceholder': 'राज्य, शहर किंवा स्थिती शोधा...',
    'infra.showing': 'दाखवत आहे',
    'infra.statesUts': 'राज्ये आणि केंद्रशासित प्रदेश',
    'infra.clickToDrill': 'शहराची माहिती पाहण्यासाठी कोणत्याही राज्यावर क्लिक करा',
    'infra.healthy': 'उत्कृष्ट',
    'infra.compromised': 'तणावग्रस्त',
    'infra.failing': 'गंभीर',
    'infra.statusAll': 'सर्व स्थिती',
    'infra.statusOperational': 'केवळ कार्यरत',
    'infra.statusDegraded': 'केवळ प्रभावित/गंभीर',
    'prior.title': 'NDMA एआय प्राधान्य व हस्तक्षेप कमांड',
    'prior.subtitle': 'आपत्तीची तीव्रता आणि लोकसंख्या जोखीम विश्लेषित करणारे निर्णय इंजिन.',
    'prior.scope': 'भौगोलिक व्याप्ती',
    'prior.allZones': 'सर्व क्षेत्रे (संपूर्ण भारत)',
    'prior.district': 'जिल्हा / शहरी क्षेत्र',
    'prior.compositeVuln': 'एकत्रित असुरक्षितता निर्देशांक',
    'prior.exposureScore': 'एक्सपोजर स्कोअर',
    'prior.sensitivityScore': 'संवेदनशीलता स्कोअर',
    'prior.adaptiveDeficit': 'अनुकूलन क्षमता तूट',
    'prior.recommendedAction': 'शिफारस केलेली NDMA/SDRF कृती',
    'prior.urgency': 'तातडीची पातळी',
    'prior.hazardProgression': '२४ तासांचा अंदाजित धोका आलेख',
    'prior.dispatchSuggestion': 'शिफारस केलेले मदत पॅकेज',
    'prior.evacuationReadiness': 'स्थलांतर सज्जता',
    'disp.title': 'रणनीतिक मदत व रसद मॅट्रिक्स',
    'disp.subtitle': 'डिपोमधून आपत्ती केंद्रांपर्यंत जलद पुरवठा समन्वयक.',
    'disp.reliefStocks': 'राज्य मदत साठा',
    'disp.activeDispatches': 'सक्रिय मदत ताफे',
    'disp.authorizeDispatch': 'आणीबाणी मदत मंजूर करा',
    'disp.noDispatches': 'मध्ये कोणतेही सक्रिय ताफे नाहीत:',
    'disp.noDispatchesDesc': 'सर्व NDRF आणि SDRF पथके सध्या राज्य गोदामांमध्ये सज्ज आहेत.',
    'disp.initiateRelief': 'मदत ताफा रवाना करा',
    'disp.warehouse': 'मूळ डेपो / गोदाम',
    'disp.target': 'लक्ष्य जिल्हा',
    'disp.transportMode': 'वाहतूक मार्ग',
    'disp.eta': 'अपेक्षित आगमन वेळ',
    'disp.status': 'मोहीम स्थिती',
    'disp.inTransit': 'मार्गावर (In Transit)',
    'disp.arrived': 'पोहचले व सक्रिय',
    'disp.teleportState': 'राज्यावर लक्ष केंद्रित करण्यासाठी जिल्ह्यावर क्लिक करा',
    'res.title': 'राष्ट्रीय व राज्य आपत्ती रसद कमांड',
    'res.subtitle': 'NDRF बटालियन, साठा, यंत्रसामग्री आणि हेलिकॉप्टर सज्जता',
    'res.ndrfBattalions': 'NDRF बटालियन',
    'res.sdrfReserves': 'SDRF साठा',
    'res.airAssets': 'हवाई संसाधने',
    'res.boatsPumps': 'बोटी आणि पंप',
    'res.rationShelter': 'रेशन आणि तात्पुरते तंबू',
    'res.powerTelecom': 'जनरेटर आणि वायरलेस सेट्स',
    'res.deploy': 'संसाधन तैनात करा',
    'res.reserveLevel': 'साठा पातळी',
    'res.readiness': 'सज्जता',
    'common.search': 'शोधा...',
    'common.filter': 'फिल्टर',
    'common.export': 'डेटा निर्यात',
    'common.refresh': 'रिफ्रेश',
    'common.close': 'बंद करा',
    'common.cancel': 'रद्द करा',
    'common.confirm': 'पुष्टी करा',
    'common.details': 'तपशील',
    'common.critical': 'अति गंभीर',
    'common.high': 'उच्च',
    'common.moderate': 'मध्यम',
    'common.low': 'सामान्य',
    'common.live': 'थेट',
  },
  ta: {
    // Tamil
    'app.title': 'பாரத் பேரிடர் பாதிப்பு இயந்திரம்',
    'app.subtitle': 'திரிவர்ண 2.0 • NDMA கட்டளை மையம்',
    'app.systemNominal': 'அமைப்பு இயல்பானது',
    'app.allSystemsSecure': 'அனைத்து அமைப்புகளும் பாதுகாப்பானவை',
    'app.nationalGrid': 'தேசிய பேரிடர் மீட்பு அமைப்பு • NDMA தந்திரோபாய கிரிட்',
    'app.selectLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'app.switchLanguage': 'மொழி',
    'nav.analytics': 'கட்டளை மற்றும் AI நுண்ணறிவு',
    'nav.vulnerabilityMap': 'பாதிப்பு வரைபடம் (GIS)',
    'nav.dispatchMap': 'பணிப்பகிர்வு & தளவாட வரைபடம்',
    'nav.resourceManagement': 'வள மேலாண்மை',
    'nav.prioritizationDashboard': 'முன்னுரிமை டாஷ்போர்டு',
    'nav.infrastructureStatus': 'உள்கட்டமைப்பு நிலை',
    'nav.nationalStandby': 'தேசிய தயார்நிலை',
    'nav.standbyDesc': '36 மாநிலங்கள் & யூனியன் பிரதேசங்கள் NDMA நிவாரண கிரிட்டுடன் இணைக்கப்பட்டுள்ளன.',
    'nav.gridActive': 'கிரிட்: செயலில்',
    'nav.hubsOnline': '68 மையங்கள் ஆன்லைனில்',
    'nav.authorized': 'NDMA அங்கீகரிக்கப்பட்டது',
    'nav.teamName': 'டீம் வாட்ச் டாக்ஸ்',
    'vuln.title': 'நகர்ப்புற பேரிடர் பாதிப்பு இயந்திரம்',
    'vuln.activeSimulation': 'செயலில் உள்ள உருவகப்படுத்துதல்',
    'vuln.disasterType': 'பேரிடர் வகை',
    'vuln.severity': 'தீவிர நிலை',
    'vuln.epicenter': 'மையப்புள்ளி',
    'vuln.radius': 'பாதிப்பு ஆரம்',
    'vuln.affectedDistricts': 'பாதிக்கப்பட்ட மாவட்டங்கள்',
    'vuln.affectedPopulation': 'பாதிக்கப்பட்ட மக்கள்',
    'vuln.criticalInfrastructure': 'ஆபத்தில் உள்ள உள்கட்டமைப்புகள்',
    'vuln.highRisk': 'அதிக ஆபத்து',
    'vuln.mediumRisk': 'நடுத்தர ஆபத்து',
    'vuln.lowRisk': 'குறைந்த ஆபத்து',
    'vuln.flood': 'வெள்ளம் & நீர் தேங்குதல்',
    'vuln.heatwave': 'கடுமையான வெப்ப அலை',
    'vuln.cyclone': 'புயல்',
    'vuln.earthquake': 'நிலநடுக்கம்',
    'infra.title': 'முக்கிய உள்கட்டமைப்பு தொலை அளவியல் மற்றும் நிலை',
    'infra.subtitle': 'ஆப்டிகல் நெட்வொர்க், வடிகால், அவசர தொடர்பு மற்றும் மின்சார அமைப்புகளின் நேரடி கண்காணிப்பு.',
    'infra.allIndiaTelemetry': 'அகில இந்திய நகர்ப்புற உள்கட்டமைப்பு அளவியல்',
    'infra.network': 'செல்லுலார் மற்றும் ஆப்டிகல் நெட்வொர்க்குகள்',
    'infra.drainage': 'மழைநீர் வடிகால் அமைப்புகள்',
    'infra.comms': 'அவசரகால தொடர்பு நெட்வொர்க்',
    'infra.power': 'உயர் மின்னழுத்த மின் கிரிட்கள்',
    'infra.state': 'மாநிலம்',
    'infra.cityDistrict': 'நகரம் / மாவட்டம்',
    'infra.lastUpdated': 'கடைசி புதுப்பிப்பு',
    'infra.vulnScore': 'ஒட்டுமொத்த பாதிப்பு மதிப்பெண்',
    'infra.searchPlaceholder': 'மாநிலம், நகரம் அல்லது நிலையைத் தேடுங்கள்...',
    'infra.showing': 'காண்பிக்கப்படுகிறது',
    'infra.statesUts': 'மாநிலங்கள் & யூனியன் பிரதேசங்கள்',
    'infra.clickToDrill': 'விவரங்களைப் பார்க்க எந்த மாநிலத்தையும் கிளிக் செய்யவும்',
    'infra.healthy': 'சிறப்பானது',
    'infra.compromised': 'பாதிக்கப்பட்டது',
    'infra.failing': 'சிக்கலானது',
    'infra.statusAll': 'அனைத்து நிலைகளும்',
    'infra.statusOperational': 'செயல்படுபவை மட்டும்',
    'infra.statusDegraded': 'பாதிக்கப்பட்டவை மட்டும்',
    'prior.title': 'NDMA AI முன்னுரிமை & தலையீட்டுக் கட்டளை',
    'prior.subtitle': 'பேரிடர் தீவிரம் மற்றும் மக்கள் தொகை பாதிப்பை பகுப்பாய்வு செய்யும் முடிவு இயந்திரம்.',
    'prior.scope': 'புவியியல் எல்லை',
    'prior.allZones': 'அனைத்து மண்டலங்களும் (இந்தியா முழுவதும்)',
    'prior.district': 'மாவட்டம் / நகர்ப்புற மண்டலம்',
    'prior.compositeVuln': 'கூட்டு பாதிப்பு குறியீடு',
    'prior.exposureScore': 'வெளிப்பாடு மதிப்பெண்',
    'prior.sensitivityScore': 'உணர்திறன் மதிப்பெண்',
    'prior.adaptiveDeficit': 'தகவமைப்பு திறன் பற்றாக்குறை',
    'prior.recommendedAction': 'பரிந்துரைக்கப்பட்ட மீட்பு நடவடிக்கை',
    'prior.urgency': 'அவசர நிலை',
    'prior.hazardProgression': '24 மணி நேர முன்னறிவிப்பு வரைபடம்',
    'prior.dispatchSuggestion': 'பரிந்துரைக்கப்பட்ட நிவாரணத் தொகுப்பு',
    'prior.evacuationReadiness': 'வெளியேற்ற தயார்நிலை',
    'disp.title': 'தந்திரோபாய நிவாரண & தளவாட வரைபடம்',
    'disp.subtitle': 'கிடங்குகளிலிருந்து பேரிடர் பகுதிகளுக்கு விரைவான நிவாரண விநியோகம்.',
    'disp.reliefStocks': 'மாநில நிவாரண கையிருப்பு',
    'disp.activeDispatches': 'செயலில் உள்ள நிவாரண வாகனங்கள்',
    'disp.authorizeDispatch': 'அவசர நிவாரணத்தை அங்கீகரிக்கவும்',
    'disp.noDispatches': 'இல் செயலில் உள்ள வாகனங்கள் இல்லை:',
    'disp.noDispatchesDesc': 'அனைத்து NDRF மற்றும் SDRF குழுக்களும் தற்போது தயார் நிலையில் உள்ளன.',
    'disp.initiateRelief': 'நிவாரணக் குழுவை அனுப்பவும்',
    'disp.warehouse': 'மூல கிடங்கு',
    'disp.target': 'இலக்கு மாவட்டம்',
    'disp.transportMode': 'போக்குவரத்து வழித்தடம்',
    'disp.eta': 'எதிர்பார்க்கப்படும் வருகை நேரம்',
    'disp.status': 'பணி நிலை',
    'disp.inTransit': 'வழியில் உள்ளது (In Transit)',
    'disp.arrived': 'வந்து சேர்ந்தது & செயலில்',
    'disp.teleportState': 'மாநிலத்தை மையப்படுத்த மாவட்டத்தை கிளிக் செய்யவும்',
    'res.title': 'தேசிய & மாநில பேரிடர் தளவாடக் கட்டளை',
    'res.subtitle': 'NDRF படைகள், இருப்புக்கள் மற்றும் ஹெலிகாப்டர் தயார்நிலை',
    'res.ndrfBattalions': 'NDRF படைகள்',
    'res.sdrfReserves': 'SDRF இருப்புக்கள்',
    'res.airAssets': 'விமானங்கள் & ஹெலிகாப்டர்கள்',
    'res.boatsPumps': 'படகுகள் & பம்புகள்',
    'res.rationShelter': 'உணவு & தற்காலிக கூடாரங்கள்',
    'res.powerTelecom': 'ஜெனரேட்டர்கள் & தகவல் தொடர்பு சாதனங்கள்',
    'res.deploy': 'வளங்களை அனுப்பவும்',
    'res.reserveLevel': 'இருப்பு நிலை',
    'res.readiness': 'செயல்பாட்டுத் தயார்நிலை',
    'common.search': 'தேடுங்கள்...',
    'common.filter': 'வடிகட்டு',
    'common.export': 'ஏற்றுமதி',
    'common.refresh': 'புதுப்பி',
    'common.close': 'மூடு',
    'common.cancel': 'ரத்துசெய்',
    'common.confirm': 'உறுதிசெய்',
    'common.details': 'விவரங்கள்',
    'common.critical': 'மிகவும் ஆபத்தானது',
    'common.high': 'அதிகம்',
    'common.moderate': 'மிதமானது',
    'common.low': 'குறைவு',
    'common.live': 'நேரலை',
  },
  ur: {
    // Urdu
    'app.title': 'بھارت ڈیزاسٹر ولنریبلٹی انجن',
    'app.subtitle': 'ترنگا 2.0 • این ڈی ایم اے کمانڈ',
    'app.systemNominal': 'سسٹم معمول کے مطابق',
    'app.allSystemsSecure': 'تمام سسٹمز محفوظ ہیں',
    'app.nationalGrid': 'قومی آفات ردعمل نظام • این ڈی ایم اے ٹیکٹیکل گرڈ',
    'app.selectLanguage': 'زبان منتخب کریں',
    'app.switchLanguage': 'زبان',
    'nav.analytics': 'کمانڈ اور اے آئی انٹیلی جنس',
    'nav.vulnerabilityMap': 'خطرہ کا نقشہ (GIS)',
    'nav.dispatchMap': 'ڈسپیچ اور لاجسٹکس نقشہ',
    'nav.resourceManagement': 'وسائل کا انتظام',
    'nav.prioritizationDashboard': 'ترجیحی ڈیش بورڈ',
    'nav.infrastructureStatus': 'بنیادی ڈھانچے کی صورتحال',
    'nav.nationalStandby': 'قومی تیاری',
    'nav.standbyDesc': '36 ریاستیں اور یو ٹیز این ڈی ایم اے ریلیف گرڈ سے منسلک ہیں۔',
    'nav.gridActive': 'گرڈ: فعال',
    'nav.hubsOnline': '68 مراکز آن لائن',
    'nav.authorized': 'این ڈی ایم اے مجاز',
    'nav.teamName': 'ٹیم واچ ڈاگز',
    'vuln.title': 'شہری خطرات کا انجن',
    'vuln.activeSimulation': 'فعال نقالی',
    'vuln.disasterType': 'آفت کی قسم',
    'vuln.severity': 'شدت کی سطح',
    'vuln.epicenter': 'مرکز آفت',
    'vuln.radius': 'اثر کا دائرہ',
    'vuln.affectedDistricts': 'متاثرہ اضلاع',
    'vuln.affectedPopulation': 'متاثرہ آبادی',
    'vuln.criticalInfrastructure': 'خطرے میں بنیادی ڈھانچہ',
    'vuln.highRisk': 'زیادہ خطرہ',
    'vuln.mediumRisk': 'درمیانہ خطرہ',
    'vuln.lowRisk': 'کم خطرہ',
    'vuln.flood': 'سیलाब اور پانی کا جماؤ',
    'vuln.heatwave': 'شدید گرمی کی لہر',
    'vuln.cyclone': 'سمندری طوفان',
    'vuln.earthquake': 'زلزلہ',
    'infra.title': 'بنیادی ڈھانچے کی ٹیلی میٹری اور حیثیت میٹرکس',
    'infra.subtitle': 'آپٹیکل نیٹ ورکس، نکاسی آب، ہنگامی مواصلات اور پاور گرڈز کی لائیو ٹریکنگ۔',
    'infra.allIndiaTelemetry': 'آل انڈیا شہری بنیادی ڈھانچہ ٹیلی میٹری',
    'infra.network': 'سیلولر اور آپٹیکل نیٹ ورکس',
    'infra.drainage': 'طوفانی نکاسی آب کے نظام',
    'infra.comms': 'ہنگامی مواصلاتی نیٹ ورک',
    'infra.power': 'ہائی وولٹیج پاور گرڈز',
    'infra.state': 'ریاست',
    'infra.cityDistrict': 'شہر / ضلع',
    'infra.lastUpdated': 'آخری تجدید',
    'infra.vulnScore': 'مجموعی خطرے کا اسکور',
    'infra.searchPlaceholder': 'ریاست، شہر یا حیثیت تلاش کریں...',
    'infra.showing': 'دکھا رہا ہے',
    'infra.statesUts': 'ریاستیں اور یو ٹیز',
    'infra.clickToDrill': 'تفصیلات کے لیے کسی بھی ریاست پر کلک کریں',
    'infra.healthy': 'بہترین',
    'infra.compromised': 'متاثرہ',
    'infra.failing': 'نازک',
    'infra.statusAll': 'تمام حالات',
    'infra.statusOperational': 'صرف فعال',
    'infra.statusDegraded': 'صرف متاثرہ/نازک',
    'prior.title': 'این ڈی ایم اے اے آئی ترجیح اور مداخلت کمانڈ',
    'prior.subtitle': 'آفت کی شدت اور آبادی کے خطرے کا تجزیہ کرنے والا فیصلہ انجن۔',
    'prior.scope': 'جغرافیائی دائرہ کار',
    'prior.allZones': 'تمام زونز (پورے بھارت میں)',
    'prior.district': 'ضلع / شہری علاقہ',
    'prior.compositeVuln': 'مجموعی کمزوری انڈیکس',
    'prior.exposureScore': 'ایکسپوژر اسکور',
    'prior.sensitivityScore': 'حساسیت کا اسکور',
    'prior.adaptiveDeficit': 'مطابقت پذیری کی صلاحیت کی کمی',
    'prior.recommendedAction': 'تجویز کردہ امدادی کارروائی',
    'prior.urgency': 'فوری ضرورت',
    'prior.hazardProgression': '24 گھنٹے کا متوقع خطرے کا گراف',
    'prior.dispatchSuggestion': 'تجویز کردہ امدادی پیکیج',
    'prior.evacuationReadiness': 'انخلاء کی تیاری',
    'disp.title': 'ٹیکٹیکل ڈسپیچ اور لاجسٹکس میٹرکس',
    'disp.subtitle': 'ڈپو سے آفت زدہ علاقوں تک تیز رفتار ترسیل کا رابطہ۔',
    'disp.reliefStocks': 'ریاستی امدادی ذخائر',
    'disp.activeDispatches': 'فعال امدادی قافلے',
    'disp.authorizeDispatch': 'ہنگامی امداد کی منظوری دیں',
    'disp.noDispatches': 'میں کوئی فعال قافلہ نہیں ہے:',
    'disp.noDispatchesDesc': 'این ڈی آر ایف اور ایس ڈی آر ایف کے تمام دستے فی الحال اسٹینڈ بائی پر ہیں۔',
    'disp.initiateRelief': 'امدادی قافلہ روانہ کریں',
    'disp.warehouse': 'مرکزی ڈپو / گودام',
    'disp.target': 'ہدف ضلع',
    'disp.transportMode': 'ٹرانسپورٹ کوریڈور',
    'disp.eta': 'پہنچنے کا متوقع وقت',
    'disp.status': 'مشن کی حیثیت',
    'disp.inTransit': 'راستے میں (In Transit)',
    'disp.arrived': 'پہنچ گیا اور فعال',
    'disp.teleportState': 'ریاست پر فوکس کرنے کے لیے ضلع پر کلک کریں',
    'res.title': 'قومی اور ریاستی ڈیزاسٹر لاجسٹکس کمانڈ',
    'res.subtitle': 'این ڈی آر ایف بٹالین، ذخائر اور ہیلی کاپٹر کی تیاری',
    'res.ndrfBattalions': 'این ڈی آر ایف بٹالین',
    'res.sdrfReserves': 'ایس ڈی آر ایف کے ذخائر',
    'res.airAssets': 'ہوا بازی کے وسائل',
    'res.boatsPumps': 'کشتی اور پمپس',
    'res.rationShelter': 'راشن اور خیمے',
    'res.powerTelecom': 'جنریٹرز اور وائرلیس سیٹ',
    'res.deploy': 'وسائل تعینات کریں',
    'res.reserveLevel': 'ذخیرہ کی سطح',
    'res.readiness': 'آپریشنل تیاری',
    'common.search': 'تلاش کریں...',
    'common.filter': 'فلٹر',
    'common.export': 'برآمد کریں',
    'common.refresh': 'تازہ کریں',
    'common.close': 'بند کریں',
    'common.cancel': 'منسوخ کریں',
    'common.confirm': 'تصدیق کریں',
    'common.details': 'تفصیلات',
    'common.critical': 'انتہائی نازک',
    'common.high': 'زیادہ',
    'common.moderate': 'معتدل',
    'common.low': 'کم',
    'common.live': 'لائیو',
  },
  gu: {
    // Gujarati
    'app.title': 'ભારત આપત્તિ સંવેદનશીલતા એન્જિન',
    'app.subtitle': 'તિરંગા 2.0 • NDMA કમાન્ડ',
    'app.systemNominal': 'સિસ્ટમ સામાન્ય',
    'app.allSystemsSecure': 'તમામ સિસ્ટમો સુરક્ષિત છે',
    'app.nationalGrid': 'રાષ્ટ્રીય આપત્તિ વ્યવસ્થાપન પ્રણાલી • NDMA વ્યૂહાત્મક ગ્રીડ',
    'app.selectLanguage': 'ભાષા પસંદ કરો',
    'app.switchLanguage': 'ભાષા',
    'nav.analytics': 'કમાન્ડ અને AI ઇન્ટેલિજન્સ',
    'nav.vulnerabilityMap': 'સંવેદનશીલતા નકશો (GIS)',
    'nav.dispatchMap': 'ડિસ્પેચ અને લોજિસ્ટિક્સ નકશો',
    'nav.resourceManagement': 'સંસાધન વ્યવસ્થાપન',
    'nav.prioritizationDashboard': 'પ્રાથમિકતા ડેશબોર્ડ',
    'nav.infrastructureStatus': 'ઇન્ફ્રાસ્ટ્રક્ચર સ્થિતિ',
    'nav.nationalStandby': 'રાષ્ટ્રીય સજ્જતા',
    'nav.standbyDesc': '36 રાજ્યો અને કેન્દ્રશાસિત પ્રદેશો NDMA ગ્રીડ સાથે જોડાયેલા છે.',
    'nav.gridActive': 'ગ્રીડ: સક્રિય',
    'nav.hubsOnline': '68 કેન્દ્રો ઑનલાઇન',
    'nav.authorized': 'NDMA અધિકૃત',
    'nav.teamName': 'ટીમ વૉચ ડૉગ્સ',
    'vuln.title': 'શહેરી આપત્તિ સંવેદનશીલતા એન્જિન',
    'vuln.activeSimulation': 'સક્રિય સિમ્યુલેશન',
    'vuln.disasterType': 'આપત્તિનો પ્રકાર',
    'vuln.severity': 'તીવ્રતા સ્તર',
    'vuln.epicenter': 'આપત્તિ કેન્દ્ર',
    'vuln.radius': 'અસર ત્રિજ્યા',
    'vuln.affectedDistricts': 'અસરગ્રસ્ત જિલ્લાઓ',
    'vuln.affectedPopulation': 'અસરગ્રસ્ત વસ્તી',
    'vuln.criticalInfrastructure': 'જોખમમાં રહેલ ઇન્ફ્રાસ્ટ્રક્ચર',
    'vuln.highRisk': 'ઉચ્ચ જોખમ',
    'vuln.mediumRisk': 'મધ્યમ જોખમ',
    'vuln.lowRisk': 'ઓછું જોખમ',
    'vuln.flood': 'પૂર અને જળબંબાકાર',
    'vuln.heatwave': 'હીટવેવ (ગરમીનું મોજું)',
    'vuln.cyclone': 'વાવાઝોડું (ચક્રવાત)',
    'vuln.earthquake': 'ધરતીકંપ',
    'infra.title': 'ઇન્ફ્રાસ્ટ્રક્ચર ટેલિમેટ્રી અને સ્ટેટસ મેટ્રિક્સ',
    'infra.subtitle': 'ઓપ્ટિકલ નેટવર્ક, ડ્રેનેજ અને પાવર ગ્રીડ્સનું રીઅલ-ટાઇમ મોનિટરિંગ.',
    'infra.allIndiaTelemetry': 'અખિલ ભારતીય શહેરી ઇન્ફ્રાસ્ટ્રક્ચર ટેલિમેટ્રી',
    'infra.network': 'સેલ્યુલર અને ઓપ્ટિકલ નેટવર્ક્સ',
    'infra.drainage': 'વરસાદી પાણી નિકાલ વ્યવસ્થા',
    'infra.comms': 'ઇમરજન્સી કોમ્યુનિકેશન નેટવર્ક',
    'infra.power': 'હાઇ-વોલ્ટેજ પાવર ગ્રીડ્સ',
    'infra.state': 'રાજ્ય',
    'infra.cityDistrict': 'શહેર / જિલ્લો',
    'infra.lastUpdated': 'છેલ્લું અપડેટ',
    'infra.vulnScore': 'કુલ સંવેદનશીલતા સ્કોર',
    'infra.searchPlaceholder': 'રાજ્ય, શહેર અથવા સ્થિતિ શોધો...',
    'infra.showing': 'દર્શાવે છે',
    'infra.statesUts': 'રાજ્યો અને કેન્દ્રશાસિત પ્રદેશો',
    'infra.clickToDrill': 'વિગતો જોવા માટે કોઈપણ રાજ્ય પર ક્લિક કરો',
    'infra.healthy': 'ઉત્તમ',
    'infra.compromised': 'પ્રભાવિત',
    'infra.failing': 'ગંભીર',
    'infra.statusAll': 'તમામ સ્થિતિઓ',
    'infra.statusOperational': 'માત્ર કાર્યરત',
    'infra.statusDegraded': 'માત્ર પ્રભાવિત/ગંભીર',
    'prior.title': 'NDMA AI પ્રાથમિકતા અને હસ્તક્ષેપ કમાન્ડ',
    'prior.subtitle': 'આપત્તિ તીવ્રતા અને વસ્તી જોખમનું વિશ્લેષણ કરતું નિર્ણય એન્જિન.',
    'prior.scope': 'ભૌગોલિક ક્ષેત્ર',
    'prior.allZones': 'તમામ ઝોન (સમગ્ર ભારતમાં)',
    'prior.district': 'જિલ્લો / શહેરી ઝોન',
    'prior.compositeVuln': 'સંયુક્ત સંવેદનશીલતા ઇન્ડેક્સ',
    'prior.exposureScore': 'એક્સપોઝર સ્કોર',
    'prior.sensitivityScore': 'સંવેદનશીલતા સ્કોર',
    'prior.adaptiveDeficit': 'અનુકૂલન ક્ષમતા ખાધ',
    'prior.recommendedAction': 'ભલામણ કરેલ NDMA/SDRF પગલાં',
    'prior.urgency': 'તાકીદ',
    'prior.hazardProgression': '24-કલાકનો અંદાજિત જોખમ ગ્રાફ',
    'prior.dispatchSuggestion': 'ભલામણ કરેલ રાહત પેકેજ',
    'prior.evacuationReadiness': 'સ્થળાંતર સજ્જતા',
    'disp.title': 'વ્યૂહાત્મક ડિસ્પેચ અને લોજિસ્ટિક્સ મેટ્રિક્સ',
    'disp.subtitle': 'ગોદામોથી આપત્તિ કેન્દ્રો સુધી ઝડપી પુરવઠો સંકલનકર્તા.',
    'disp.reliefStocks': 'રાજ્ય રાહત સ્ટોક',
    'disp.activeDispatches': 'સક્રિય રાહત કાફલાઓ',
    'disp.authorizeDispatch': 'ઇમરજન્સી રાહત મંજૂર કરો',
    'disp.noDispatches': 'માં કોઈ સક્રિય કાફલો નથી:',
    'disp.noDispatchesDesc': 'તમામ NDRF અને SDRF ટીમો હાલમાં સ્ટેન્ડબાય પર છે.',
    'disp.initiateRelief': 'રાહત કાફલો રવાના કરો',
    'disp.warehouse': 'મૂળ ડિપો / ગોદામ',
    'disp.target': 'લક્ષ્ય જિલ્લો',
    'disp.transportMode': 'પરિવહન કોરિડોર',
    'disp.eta': 'આગમનનો અંદાજિત સમય',
    'disp.status': 'મિશન સ્થિતિ',
    'disp.inTransit': 'રસ્તામાં (In Transit)',
    'disp.arrived': 'પહોંચી ગયું અને સક્રિય',
    'disp.teleportState': 'રાજ્ય પર ધ્યાન કેન્દ્રિત કરવા જિલ્લા પર ક્લિક કરો',
    'res.title': 'રાષ્ટ્રીય અને રાજ્ય આપત્તિ લોજિસ્ટિક્સ કમાન્ડ',
    'res.subtitle': 'NDRF બટાલિયનો, સ્ટોક અને હેલિકોપ્ટર સજ્જતા',
    'res.ndrfBattalions': 'NDRF બટાલિયનો',
    'res.sdrfReserves': 'SDRF સ્ટોક',
    'res.airAssets': 'હવાઈ સંસાધનો',
    'res.boatsPumps': 'બોટ અને પંપ',
    'res.rationShelter': 'રાશન અને તંબુ',
    'res.powerTelecom': 'જનરેટર અને વાયરલેસ સેટ્સ',
    'res.deploy': 'સંસાધનો તૈનાત કરો',
    'res.reserveLevel': 'સ્ટોક સ્તર',
    'res.readiness': 'ઓપરેશનલ સજ્જતા',
    'common.search': 'શોધો...',
    'common.filter': 'ફિલ્ટર',
    'common.export': 'નિકાસ',
    'common.refresh': 'રીફ્રેશ',
    'common.close': 'બંધ કરો',
    'common.cancel': 'રદ કરો',
    'common.confirm': 'પુષ્ટિ કરો',
    'common.details': 'વિગતો',
    'common.critical': 'અતિ ગંભીર',
    'common.high': 'ઉચ્ચ',
    'common.moderate': 'મધ્યમ',
    'common.low': 'ઓછું',
    'common.live': 'લાઇવ',
  },
  kn: {
    // Kannada
    'app.title': 'ಭಾರತ ವಿಪತ್ತು ದುರ್ಬಲತೆ ಎಂಜಿನ್',
    'app.subtitle': 'ತ್ರಿವರ್ಣ 2.0 • NDMA ಕಮಾಂಡ್',
    'app.systemNominal': 'ವ್ಯವಸ್ಥೆ ಸಾಮಾನ್ಯವಾಗಿದೆ',
    'app.allSystemsSecure': 'ಎಲ್ಲಾ ವ್ಯವಸ್ಥೆಗಳು ಸುರಕ್ಷಿತವಾಗಿವೆ',
    'app.nationalGrid': 'ರಾಷ್ಟ್ರೀಯ ವಿಪತ್ತು ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ • NDMA ಯುದ್ಧತಂತ್ರದ ಗ್ರಿಡ್',
    'app.selectLanguage': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'app.switchLanguage': 'ಭಾಷೆ',
    'nav.analytics': 'ಕಮಾಂಡ್ ಮತ್ತು AI ಇಂಟೆಲಿಜೆನ್ಸ್',
    'nav.vulnerabilityMap': 'ದುರ್ಬಲತೆ ನಕ್ಷೆ (GIS)',
    'nav.dispatchMap': 'ರವಾನೆ ಮತ್ತು ಲಾಜಿಸ್ಟಿಕ್ಸ್ ನಕ್ಷೆ',
    'nav.resourceManagement': 'ಸಂಪನ್ಮೂಲ ನಿರ್ವಹಣೆ',
    'nav.prioritizationDashboard': 'ಆದ್ಯತಾ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.infrastructureStatus': 'ಮೂಲಸೌಕರ್ಯ ಸ್ಥಿತಿ',
    'nav.nationalStandby': 'ರಾಷ್ಟ್ರೀಯ ಸನ್ನದ್ಧತೆ',
    'nav.standbyDesc': '36 ರಾಜ್ಯಗಳು ಮತ್ತು ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು NDMA ಗ್ರಿಡ್‌ನೊಂದಿಗೆ ಸಂಪರ್ಕ ಹೊಂದಿವೆ.',
    'nav.gridActive': 'ಗ್ರಿಡ್: ಸಕ್ರಿಯ',
    'nav.hubsOnline': '68 ಕೇಂದ್ರಗಳು ಆನ್‌ಲೈನ್',
    'nav.authorized': 'NDMA ಅಧಿಕೃತ',
    'nav.teamName': 'ಟೀಮ್ ವಾಚ್ ಡಾಗ್ಸ್',
    'vuln.title': 'ನಗರ ವಿಪತ್ತು ದುರ್ಬಲತೆ ವ್ಯವಸ್ಥೆ',
    'vuln.activeSimulation': 'ಪ್ರಸ್ತುತ ವಿಪತ್ತು ಅನುಕರಣೆ',
    'vuln.disasterType': 'ವಿಪತ್ತಿನ ಪ್ರಕಾರ',
    'vuln.severity': 'ತೀವ್ರತೆಯ ಮಟ್ಟ',
    'vuln.epicenter': 'ವಿಪತ್ತು ಕೇಂದ್ರ',
    'vuln.radius': 'ಪ್ರಭಾವದ ತ್ರಿಜ್ಯ',
    'vuln.affectedDistricts': 'ಬಾಧಿತ ಜಿಲ್ಲೆಗಳು',
    'vuln.affectedPopulation': 'ಬಾಧಿತ ಜನಸಂಖ್ಯೆ',
    'vuln.criticalInfrastructure': 'ಅಪಾಯದಲ್ಲಿರುವ ಮೂಲಸೌಕರ್ಯ',
    'vuln.highRisk': 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
    'vuln.mediumRisk': 'ಮಧ್ಯಮ ಅಪಾಯ',
    'vuln.lowRisk': 'ಕಡಿಮೆ ಅಪಾಯ',
    'vuln.flood': 'ಪ್ರವಾಹ ಮತ್ತು ಮುಳುಗಡೆ',
    'vuln.heatwave': 'ತೀವ್ರ ಶಾಖದ ಅಲೆ',
    'vuln.cyclone': 'ಚಂಡಮಾರುತ',
    'vuln.earthquake': 'ಭೂಕಂಪ',
    'infra.title': 'ಮೂಲಸೌಕರ್ಯ ಟೆಲಿಮೆಟ್ರಿ ಮತ್ತು ಸ್ಥಿತಿ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    'infra.subtitle': 'ಆಪ್ಟಿಕಲ್ ನೆಟ್‌ವರ್ಕ್‌ಗಳು, ಒಳಚರಂಡಿ ಮತ್ತು ವಿದ್ಯುತ್ ಗ್ರಿಡ್‌ಗಳ ನೈಜ-ಸಮಯದ ಟ್ರ್ಯಾಕಿಂಗ್.',
    'infra.allIndiaTelemetry': 'ಅಖಿಲ ಭಾರತ ನಗರ ಮೂಲಸೌಕರ್ಯ ಟೆಲಿಮೆಟ್ರಿ',
    'infra.network': 'ಸೆಲ್ಯುಲಾರ್ ಮತ್ತು ಆಪ್ಟಿಕಲ್ ನೆಟ್‌ವರ್ಕ್‌ಗಳು',
    'infra.drainage': 'ಮಳೆನೀರು ಒಳಚರಂಡಿ ವ್ಯವಸ್ಥೆಗಳು',
    'infra.comms': 'ತುರ್ತು ಸಂವಹನ ಜಾಲ',
    'infra.power': 'ಹೈ-ವೋಲ್ಟೇಜ್ ಪವರ್ ಗ್ರಿಡ್‌ಗಳು',
    'infra.state': 'ರಾಜ್ಯ',
    'infra.cityDistrict': 'ನಗರ / ಜಿಲ್ಲೆ',
    'infra.lastUpdated': 'ಕೊನೆಯ ನವೀಕರಣ',
    'infra.vulnScore': 'ಒಟ್ಟು ದುರ್ಬಲತೆ ಸ್ಕೋರ್',
    'infra.searchPlaceholder': 'ರಾಜ್ಯ, ನಗರ ಅಥವಾ ಸ್ಥಿತಿಯನ್ನು ಹುಡುಕಿ...',
    'infra.showing': 'ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    'infra.statesUts': 'ರಾಜ್ಯಗಳು ಮತ್ತು ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು',
    'infra.clickToDrill': 'ವಿವರಗಳನ್ನು ನೋಡಲು ಯಾವುದೇ ರಾಜ್ಯವನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ',
    'infra.healthy': 'ಉತ್ತಮ',
    'infra.compromised': 'ಬಾಧಿತ',
    'infra.failing': 'ಗಂಭೀರ',
    'infra.statusAll': 'ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು',
    'infra.statusOperational': 'ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿರುವವು ಮಾತ್ರ',
    'infra.statusDegraded': 'ಬಾಧಿತ/ಗಂಭೀರ ಮಾತ್ರ',
    'prior.title': 'NDMA AI ಆದ್ಯತಾ ಕಮಾಂಡ್',
    'prior.subtitle': 'ವಿಪತ್ತು ತೀವ್ರತೆ ಮತ್ತು ಜನಸಂಖ್ಯೆಯ ಅಪಾಯವನ್ನು ವಿಶ್ಲೇಷಿಸುವ ನಿರ್ಧಾರ ಎಂಜಿನ್.',
    'prior.scope': 'ಭೌಗೋಳಿಕ ವ್ಯಾಪ್ತಿ',
    'prior.allZones': 'ಎಲ್ಲಾ ವಲಯಗಳು (ಭಾರತದಾದ್ಯಂತ)',
    'prior.district': 'ಜಿಲ್ಲೆ / ನಗರ ವಲಯ',
    'prior.compositeVuln': 'ಸಂಯೋಜಿತ ದುರ್ಬಲತೆ ಸೂಚ್ಯಂಕ',
    'prior.exposureScore': 'ಎಕ್ಸ್‌ಪೋಸರ್ ಸ್ಕೋರ್',
    'prior.sensitivityScore': 'ಸೂಕ್ಷ್ಮತೆ ಸ್ಕೋರ್',
    'prior.adaptiveDeficit': 'ಹೊಂದಾಣಿಕೆ ಸಾಮರ್ಥ್ಯ ಕೊರತೆ',
    'prior.recommendedAction': 'ಶಿಫಾರಸು ಮಾಡಿದ ಪರಿಹಾರ ಕ್ರಮ',
    'prior.urgency': 'ತುರ್ತುಸ್ಥಿತಿ',
    'prior.hazardProgression': '24-ಗಂಟೆಗಳ ಮುನ್ಸೂಚನಾ ಗ್ರಾಫ್',
    'prior.dispatchSuggestion': 'ಶಿಫಾರಸು ಮಾಡಲಾದ ಪರಿಹಾರ ಪ್ಯಾಕೇಜ್',
    'prior.evacuationReadiness': 'ಸ್ಥಳಾಂತರಿಸುವ ಸನ್ನದ್ಧತೆ',
    'disp.title': 'ಯುದ್ಧತಂತ್ರದ ಪರಿಹಾರ ಮತ್ತು ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    'disp.subtitle': 'ಗೋದಾಮುಗಳಿಂದ ವಿಪತ್ತು ಪ್ರದೇಶಗಳಿಗೆ ತ್ವರಿತ ಪರಿಹಾರ ಪೂರೈಕೆ.',
    'disp.reliefStocks': 'ರಾಜ್ಯ ಪರಿಹಾರ ದಾಸ್ತಾನು',
    'disp.activeDispatches': 'ಸಕ್ರಿಯ ಪರಿಹಾರ ಬೆಂಗಾವಲುಗಳು',
    'disp.authorizeDispatch': 'ತುರ್ತು ಪರಿಹಾರವನ್ನು ಅನುಮೋದಿಸಿ',
    'disp.noDispatches': 'ನಲ್ಲಿ ಯಾವುದೇ ಸಕ್ರಿಯ ಬೆಂಗಾವಲುಗಳಿಲ್ಲ:',
    'disp.noDispatchesDesc': 'ಎಲ್ಲಾ NDRF ಮತ್ತು SDRF ತಂಡಗಳು ಪ್ರಸ್ತುತ ಸನ್ನದ್ಧ ಸ್ಥಿತಿಯಲ್ಲಿವೆ.',
    'disp.initiateRelief': 'ಪರಿಹಾರ ತಂಡವನ್ನು ಕಳುಹಿಸಿ',
    'disp.warehouse': 'ಮೂಲ ಡಿಪೋ / ಗೋದಾಮು',
    'disp.target': 'ಗುರಿ ಜಿಲ್ಲೆ',
    'disp.transportMode': 'ಸಾರಿಗೆ ಕಾರಿಡಾರ್',
    'disp.eta': 'ಅಂದಾಜು ಆಗಮನದ ಸಮಯ',
    'disp.status': 'ಮಿಷನ್ ಸ್ಥಿತಿ',
    'disp.inTransit': 'ದಾರಿಯಲ್ಲಿದೆ (In Transit)',
    'disp.arrived': 'ತಲುಪಿದೆ ಮತ್ತು ಸಕ್ರಿಯ',
    'disp.teleportState': 'ರಾಜ್ಯವನ್ನು ಕೇಂದ್ರೀಕರಿಸಲು ಜಿಲ್ಲೆಯನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ',
    'res.title': 'ರಾಷ್ಟ್ರೀಯ ಮತ್ತು ರಾಜ್ಯ ವಿಪತ್ತು ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಕಮಾಂಡ್',
    'res.subtitle': 'NDRF ಬೆಟಾಲಿಯನ್‌ಗಳು, ದಾಸ್ತಾನು ಮತ್ತು ಹೆಲಿಕಾಪ್ಟರ್ ಸನ್ನದ್ಧತೆ',
    'res.ndrfBattalions': 'NDRF ಬೆಟಾಲಿಯನ್‌ಗಳು',
    'res.sdrfReserves': 'SDRF ದಾಸ್ತಾನು',
    'res.airAssets': 'ವಾಯುಯಾನ ಸಂಪನ್ಮೂಲಗಳು',
    'res.boatsPumps': 'ದೋಣಿಗಳು ಮತ್ತು ಪಂಪ್‌ಗಳು',
    'res.rationShelter': 'ರೇಷನ್ ಮತ್ತು ತಾತ್ಕಾಲಿಕ ಡೇರೆಗಳು',
    'res.powerTelecom': 'ಜನರೇಟರ್‌ಗಳು ಮತ್ತು ಸಂವಹನ ಸೆಟ್‌ಗಳು',
    'res.deploy': 'ಸಂಪನ್ಮೂಲಗಳನ್ನು ನಿಯೋಜಿಸಿ',
    'res.reserveLevel': 'ದಾಸ್ತಾನು ಮಟ್ಟ',
    'res.readiness': 'ಕಾರ್ಯಾಚರಣೆ ಸನ್ನದ್ಧತೆ',
    'common.search': 'ಹುಡುಕಿ...',
    'common.filter': 'ಫಿಲ್ಟರ್',
    'common.export': 'ರಫ್ತು',
    'common.refresh': 'ರಿಫ್ರೆಶ್',
    'common.close': 'ಮುಚ್ಚಿ',
    'common.cancel': 'ರದ್ದುಮಾಡಿ',
    'common.confirm': 'ಖಚಿತಪಡಿಸಿ',
    'common.details': 'ವಿವರಗಳು',
    'common.critical': 'ಅತ್ಯಂತ ಗಂಭೀರ',
    'common.high': 'ಹೆಚ್ಚು',
    'common.moderate': 'ಮಧ್ಯಮ',
    'common.low': 'ಕಡಿಮೆ',
    'common.live': 'ಲೈವ್',
  },
  ml: {
    // Malayalam
    'app.title': 'ഭാരത് ദുരന്ത സാധ്യതാ എഞ്ചിൻ',
    'app.subtitle': 'ത്രിവർണ്ണ 2.0 • NDMA കമാൻഡ്',
    'app.systemNominal': 'സിസ്റ്റം സാധാരണ നിലയിലാണ്',
    'app.allSystemsSecure': 'എല്ലാ സിസ്റ്റങ്ങളും സുരക്ഷിതമാണ്',
    'app.nationalGrid': 'ദേശീയ ദുരന്ത നിവാരണ സംവിധാനം • NDMA തന്ത്രപരമായ ഗ്രിഡ്',
    'app.selectLanguage': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    'app.switchLanguage': 'ഭാഷ',
    'nav.analytics': 'കമാൻഡ് & AI ഇന്റലിജൻസ്',
    'nav.vulnerabilityMap': 'ദുരന്ത സാധ്യതാ ഭൂപടം (GIS)',
    'nav.dispatchMap': 'റിലീഫ് വിന്യാസ ഭൂപടം',
    'nav.resourceManagement': 'വിഭവ മാനേജ്മെന്റ്',
    'nav.prioritizationDashboard': 'മുൻഗണനാ ഡാഷ്‌ബോർഡ്',
    'nav.infrastructureStatus': 'അടിസ്ഥാന സൗകര്യ നില',
    'nav.nationalStandby': 'ദേശീയ സന്നദ്ധത',
    'nav.standbyDesc': '36 സംസ്ഥാനങ്ങളും കേന്ദ്രഭരണ പ്രദേശങ്ങളും NDMA ഗ്രിഡുമായി ബന്ധിപ്പിച്ചിരിക്കുന്നു.',
    'nav.gridActive': 'ഗ്രിഡ്: സജീവം',
    'nav.hubsOnline': '68 കേന്ദ്രങ്ങൾ ഓൺലൈൻ',
    'nav.authorized': 'NDMA അംഗീകൃതം',
    'nav.teamName': 'ടീം വാച്ച് ഡോഗ്സ്',
    'vuln.title': 'നഗര ദുരന്ത സാധ്യതാ എഞ്ചിൻ',
    'vuln.activeSimulation': 'നിലവിലെ ദുരന്ത സിമുലേഷൻ',
    'vuln.disasterType': 'ദുരന്തത്തിന്റെ തരം',
    'vuln.severity': 'തീവ്രത',
    'vuln.epicenter': 'ദുരന്ത കേന്ദ്രം',
    'vuln.radius': 'പ്രഭവ പരിധി',
    'vuln.affectedDistricts': 'ബാധിച്ച ജില്ലകൾ',
    'vuln.affectedPopulation': 'ബാധിച്ച ജനസംഖ്യ',
    'vuln.criticalInfrastructure': 'അപകടസാധ്യതയുള്ള സൗകര്യങ്ങൾ',
    'vuln.highRisk': 'ഉയർന്ന അപകടസാധ്യത',
    'vuln.mediumRisk': 'ഇടത്തരം അപകടസാധ്യത',
    'vuln.lowRisk': 'കുറഞ്ഞ അപകടസാധ്യത',
    'vuln.flood': 'വെള്ളപ്പൊക്കവും വെള്ളക്കെട്ടും',
    'vuln.heatwave': 'കഠിനമായ ഉഷ്ണതരംഗം',
    'vuln.cyclone': 'ചുഴലിക്കാറ്റ്',
    'vuln.earthquake': 'ഭൂകമ്പം',
    'infra.title': 'അടിസ്ഥാന സൗകര്യ ടെലിമെട്രി & സ്റ്റാറ്റസ് മാട്രിക്സ്',
    'infra.subtitle': 'ഒപ്റ്റിക്കൽ നെറ്റ്‌വർക്കുകൾ, ഡ്രെയിനേജ്, വൈദ്യുതി ഗ്രിഡുകൾ എന്നിവയുടെ തത്സമയ നിരീക്ഷണം.',
    'infra.allIndiaTelemetry': 'അഖിലേന്ത്യാ നഗര അടിസ്ഥാന സൗകര്യ ടെലിമെട്രി',
    'infra.network': 'സെല്ലുലാർ & ഒപ്റ്റിക്കൽ നെറ്റ്‌വർക്കുകൾ',
    'infra.drainage': 'മഴവെള്ള ഡ്രെയിനേജ് സംവിധാനങ്ങൾ',
    'infra.comms': 'അടിയന്തര ആശയവിനിമയ ശൃംഖല',
    'infra.power': 'ഹൈ-വോൾട്ടേജ് പവർ ഗ്രിഡുകൾ',
    'infra.state': 'സംസ്ഥാനം',
    'infra.cityDistrict': 'നഗരം / ജില്ല',
    'infra.lastUpdated': 'അവസാനം പുതുക്കിയത്',
    'infra.vulnScore': 'മൊത്തം സാധ്യതാ സ്കോർ',
    'infra.searchPlaceholder': 'സംസ്ഥാനം, നഗരം അല്ലെങ്കിൽ നില തിരയുക...',
    'infra.showing': 'കാണിക്കുന്നത്',
    'infra.statesUts': 'സംസ്ഥാനങ്ങളും കേന്ദ്രഭരണ പ്രദേശങ്ങളും',
    'infra.clickToDrill': 'വിവരങ്ങൾ കാണാൻ ഏതെങ്കിലും സംസ്ഥാനത്ത് ക്ലിക്ക് ചെയ്യുക',
    'infra.healthy': 'മികച്ചത്',
    'infra.compromised': 'ബാധിക്കപ്പെട്ടത്',
    'infra.failing': 'ഗുരുതരം',
    'infra.statusAll': 'എല്ലാ നിലകളും',
    'infra.statusOperational': 'പ്രവർത്തിക്കുന്നവ മാത്രം',
    'infra.statusDegraded': 'ഗുരുതരമായവ മാത്രം',
    'prior.title': 'NDMA AI മുൻഗണനാ കമാൻഡ്',
    'prior.subtitle': 'ദുരന്ത തീവ്രതയും ജനസംഖ്യാ അപകടസാധ്യതയും വിശകലനം ചെയ്യുന്ന സിസ്റ്റം.',
    'prior.scope': 'ഭൂമിശാസ്ത്രപരമായ പരിധി',
    'prior.allZones': 'എല്ലാ മേഖലകളും (ഇന്ത്യയിലുടനീളം)',
    'prior.district': 'ജില്ല / നഗര മേഖല',
    'prior.compositeVuln': 'സംയോജിത സാധ്യതാ സൂചിക',
    'prior.exposureScore': 'എക്‌സ്‌പോഷർ സ്കോർ',
    'prior.sensitivityScore': 'സെൻസിറ്റിവിറ്റി സ്കോർ',
    'prior.adaptiveDeficit': 'അനുകൂലന ശേഷിയിലെ കുറവ്',
    'prior.recommendedAction': 'ശുപാർശ ചെയ്ത ദുരിതാശ്വാസ നടപടി',
    'prior.urgency': 'അടിയന്തിരത',
    'prior.hazardProgression': '24 മണിക്കൂർ പ്രവചന ഗ്രാഫ്',
    'prior.dispatchSuggestion': 'ശുപാർശ ചെയ്ത റിലീഫ് പാക്കേജ്',
    'prior.evacuationReadiness': 'ഒഴിപ്പിക്കൽ സന്നദ്ധത',
    'disp.title': 'തന്ത്രപരമായ റിലീഫ് & ലോജിസ്റ്റിക്സ് മാട്രിക്സ്',
    'disp.subtitle': 'ഡിപ്പോകളിൽ നിന്ന് ദുരന്തബാധിത പ്രദേശങ്ങളിലേക്ക് വേഗത്തിലുള്ള വിതരണം.',
    'disp.reliefStocks': 'സംസ്ഥാന റിലീഫ് സ്റ്റോക്ക്',
    'disp.activeDispatches': 'സജീവ റിലീഫ് വാഹനവ്യൂഹം',
    'disp.authorizeDispatch': 'അടിയന്തര ദുരിതാശ്വാസം അനുവദിക്കുക',
    'disp.noDispatches': 'ൽ സജീവ വാഹനങ്ങളില്ല:',
    'disp.noDispatchesDesc': 'എല്ലാ എൻഡിആർഎഫ്, എസ്ഡിആർഎഫ് ടീമുകളും നിലവിൽ സജ്ജമാണ്.',
    'disp.initiateRelief': 'റിലീഫ് സംഘത്തെ അയക്കുക',
    'disp.warehouse': 'ഉറവിട ഡിപ്പോ / വെയർഹൗസ്',
    'disp.target': 'ലക്ഷ്യ ജില്ല',
    'disp.transportMode': 'ഗതാഗത പാത',
    'disp.eta': 'എത്തിച്ചേരുന്ന സമയം',
    'disp.status': 'ദൗത്യ നില',
    'disp.inTransit': 'യാത്രാമധ്യേ (In Transit)',
    'disp.arrived': 'എത്തിച്ചേർന്നു & സജീവം',
    'disp.teleportState': 'സംസ്ഥാനത്ത് ശ്രദ്ധ കേന്ദ്രീകരിക്കാൻ ജില്ലയിൽ ക്ലിക്ക് ചെയ്യുക',
    'res.title': 'ദേശീയ & സംസ്ഥാന ദുരന്ത ലോജിസ്റ്റിക്സ് കമാൻഡ്',
    'res.subtitle': 'NDRF ബറ്റാലിയനുകൾ, സ്റ്റോക്ക്, ഹെലികോപ്റ്റർ സന്നദ്ധത',
    'res.ndrfBattalions': 'NDRF ബറ്റാലിയനുകൾ',
    'res.sdrfReserves': 'SDRF കരുതൽ ശേഖരം',
    'res.airAssets': 'വ്യോമയാന സൗകര്യങ്ങൾ',
    'res.boatsPumps': 'ബോട്ടുകളും പമ്പുകളും',
    'res.rationShelter': 'ഭക്ഷണവും താൽക്കാലിക ടെന്റുകളും',
    'res.powerTelecom': 'ജനറേറ്ററുകളും വയർലെസ് സെറ്റുകളും',
    'res.deploy': 'വിഭവങ്ങൾ വിന്യസിക്കുക',
    'res.reserveLevel': 'സ്റ്റോക്ക് ലെവൽ',
    'res.readiness': 'പ്രവർത്തന സന്നദ്ധത',
    'common.search': 'തിരയുക...',
    'common.filter': 'ഫിൽട്ടർ',
    'common.export': 'എക്സ്പോർട്ട്',
    'common.refresh': 'പുതുക്കുക',
    'common.close': 'അടയ്ക്കുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.confirm': 'സ്ഥിരീകരിക്കുക',
    'common.details': 'വിശദാംശങ്ങൾ',
    'common.critical': 'വളരെ ഗുരുതരം',
    'common.high': 'ഉയർന്നത്',
    'common.moderate': 'ഇടത്തരം',
    'common.low': 'കുറഞ്ഞത്',
    'common.live': 'തത്സമയം',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  currentLanguageInfo: LanguageInfo;
  availableLanguages: LanguageInfo[];
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem('bharat_vuln_lang');
      if (saved && TOP_10_LANGUAGES.some((l) => l.code === saved)) {
        return saved as LanguageCode;
      }
    } catch {
      // ignore
    }
    return 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('bharat_vuln_lang', lang);
      document.documentElement.lang = lang;
    } catch {
      // ignore
    }
  };

  useEffect(() => {
    try {
      document.documentElement.lang = language;
    } catch {
      // ignore
    }
  }, [language]);

  const currentLanguageInfo =
    TOP_10_LANGUAGES.find((l) => l.code === language) || TOP_10_LANGUAGES[0];

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const enDict = TRANSLATIONS['en'];
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currentLanguageInfo,
        availableLanguages: TOP_10_LANGUAGES,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
